name: build+push

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '18 22 * * */2'
  workflow_dispatch:

env:
  platforms: linux/386, linux/amd64

jobs:
  check:
    name: check for new release of nextcloud
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
            
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/nextcloud:apache
          image: glopix/nextcloud-docker-with-php-smb

  build:
    name: build new docker image
    needs: check

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.platforms }}
          push: true
          tags: glopix/nextcloud-docker-with-php-smb:latest
          
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
