name: Build and push images

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '44 21 */2 * *'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build regardless of base image update'
        required: true
        default: 'no'
        type: choice
        options:
          - "no"
          - "yes"

jobs:
  check:
    name: check for new release of nextcloud
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}             
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v3
        with:
          base-image: library/nextcloud:apache
          image: glopix/nextcloud-docker-with-php-smb

  build:
    name: build new docker image
    needs: check
    if: needs.check.outputs.needs-updating == 'true' || github.event.inputs.force_build == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          push: true
          tags: glopix/nextcloud-docker-with-php-smb:latest
          cache-from: type=registry,ref=glopix/nextcloud-docker-with-php-smb:latest
          cache-to: type=inline
          
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


  save-build-info:
    name: save build info
    needs: [check, build]
    runs-on: ubuntu-latest
    if: needs.build.result == 'success' && needs.build.result != 'skipped'
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          ref: gh-workflows

      - name: save last image build date and release date to files
        run: |
            TODAY=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            echo "$TODAY" > ./gh-workflow_image-build-date.txt

      - name: Commit updated release data
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: gh-workflows
          file_pattern: 'gh-workflow_*.txt'
          commit_message: "Update stored release info"
          commit_user_name: GitHub Actions Bot
          commit_user_email: github-actions-bot@none.dom
          commit_author: GitHub Actions Bot <github-actions-bot@none.dom>
          create_branch: true
